In [1]:
import torch

In [2]:
torch.empty(2,3)

tensor([[ 1.5968e+30,  4.4232e-41, -3.8844e-21],
        [ 4.4231e-41,  1.4700e+31,  4.4232e-41]])

In [4]:
a=torch.empty(2,3)
type(a)

torch.Tensor

In [5]:
torch.ones(3,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [6]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.rand(2,3) # between o to 1

tensor([[0.7454, 0.2960, 0.8290],
        [0.3681, 0.7481, 0.2585]])

In [9]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
torch.tensor([[1,2,3,4],[1,1,1,1]]) # mannaul value - iterable list or tuple

tensor([[1, 2, 3, 4],
        [1, 1, 1, 1]])

In [12]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [15]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [16]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [17]:
torch.full((3,3),6)

tensor([[6, 6, 6],
        [6, 6, 6],
        [6, 6, 6]])

# tensor shapes

In [18]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
x.shape

torch.Size([2, 3])

In [20]:
torch.__version__

'2.5.1+cu121'

In [21]:
torch.empty_like(x)

tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831],
        [7954801838398993778, 2459029315949324647, 4122310119171646521]])

In [22]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [23]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [34]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# tensor datatype

datatype

In [25]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [26]:
x.dtype

torch.int64

In [30]:
torch.tensor([1.0,2.0],dtype=torch.int32)

tensor([1, 2], dtype=torch.int32)

In [31]:
torch.tensor([1,2,3],dtype=torch.float32)

tensor([1., 2., 3.])

In [32]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# math operations on tensors

# scaler operations

In [35]:
x=torch.rand(2,2)

In [36]:
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [37]:
x+2

tensor([[2.7118, 2.7876],
        [2.4183, 2.9014]])

In [38]:
x-1

tensor([[-0.2882, -0.2124],
        [-0.5817, -0.0986]])

In [39]:
x*5

tensor([[3.5588, 3.9379],
        [2.0915, 4.5071]])

In [40]:
x*100

tensor([[71.1765, 78.7581],
        [41.8305, 90.1415]])

In [42]:
x/7

tensor([[0.1017, 0.1125],
        [0.0598, 0.1288]])

In [43]:
x*200

tensor([[142.3531, 157.5161],
        [ 83.6611, 180.2830]])

In [44]:
x%2

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [45]:
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

# element wise operatiosn

In [51]:
a=torch.rand((2,2))
b=torch.rand((2,2))

In [52]:
a


tensor([[0.4440, 0.9478],
        [0.7445, 0.4892]])

In [53]:
b

tensor([[0.2426, 0.7003],
        [0.5277, 0.2472]])

In [54]:
a+b

tensor([[0.6866, 1.6482],
        [1.2722, 0.7364]])

In [55]:
a-b

tensor([[0.2015, 0.2475],
        [0.2168, 0.2420]])

In [56]:
a*b

tensor([[0.1077, 0.6638],
        [0.3929, 0.1209]])

In [57]:
a/b

tensor([[1.8306, 1.3534],
        [1.4108, 1.9791]])

In [58]:
a**b

tensor([[0.8212, 0.9632],
        [0.8558, 0.8380]])

In [60]:
c=torch.tensor([[1,-2],[33,4]])

In [61]:
c

tensor([[ 1, -2],
        [33,  4]])

In [62]:
torch.abs(c)

tensor([[ 1,  2],
        [33,  4]])

In [63]:
torch.neg(c)

tensor([[ -1,   2],
        [-33,  -4]])

In [64]:
torch.round(c)

tensor([[ 1, -2],
        [33,  4]])

In [65]:
torch.ceil(c)

tensor([[ 1, -2],
        [33,  4]])

In [66]:
d=torch.tensor([1.1,2.2,3.3])

In [67]:
torch.ceil(d)

tensor([2., 3., 4.])

In [68]:
torch.floor(d)

tensor([1., 2., 3.])

In [69]:
torch.clamp(c,min=2,max=3)

tensor([[2, 2],
        [3, 3]])

# reduction operations

In [70]:
e=torch.randint(size=(3,3),low=0,high=10)

In [71]:
e

tensor([[0, 9, 5],
        [7, 3, 9],
        [4, 0, 5]])

In [72]:
torch.sum(e)

tensor(42)

In [73]:
torch.sum(e,dim=0)

tensor([11, 12, 19])

In [74]:
torch.sum(e,dim=1)

tensor([14, 19,  9])

In [76]:
torch.mean(e.to(torch.float32))

tensor(4.6667)

In [77]:
torch.mean(e.to(torch.float32),dim=0)

tensor([3.6667, 4.0000, 6.3333])

In [78]:
torch.median(e)

tensor(5)

In [79]:
torch.min(e)

tensor(0)

In [80]:
torch.max(e)

tensor(9)

In [81]:
torch.prod(e)

tensor(0)

In [83]:
torch.std(e.to(torch.float32))

tensor(3.3541)

In [85]:
torch.var(e.to(torch.float32))

tensor(11.2500)

In [87]:
e

tensor([[0, 9, 5],
        [7, 3, 9],
        [4, 0, 5]])

In [86]:
torch.argmax(e)

tensor(1)

In [88]:
torch.argmin(e)

tensor(0)

#matrix operations

In [89]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)

In [90]:
f

tensor([[7, 5, 9],
        [9, 7, 5]])

In [91]:
g

tensor([[9, 8],
        [9, 7],
        [9, 2]])

In [92]:
torch.matmul(f,g)

tensor([[189, 109],
        [189, 131]])

In [95]:
torch.dot(torch.tensor([2,3]),torch.tensor([2,1]))

tensor(7)

In [96]:
torch.transpose(f,0,1)

tensor([[7, 9],
        [5, 7],
        [9, 5]])

In [105]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)

In [106]:
h

tensor([[6., 7., 7.],
        [8., 3., 6.],
        [1., 5., 5.]])

In [107]:
torch.det(h)

tensor(-69.0000)

In [108]:
torch.inverse(h)

tensor([[ 2.1739e-01,  2.7450e-08, -3.0435e-01],
        [ 4.9275e-01, -3.3333e-01, -2.8985e-01],
        [-5.3623e-01,  3.3333e-01,  5.5072e-01]])

# comparsion operations

In [121]:
f=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
g=torch.randint(size=(2,3),low=0,high=10)

In [111]:
print(f)
print(g)

tensor([[8, 4, 7],
        [2, 3, 8]])
tensor([[5, 6, 2],
        [9, 5, 0]])


In [112]:
f>g

tensor([[ True, False,  True],
        [False, False,  True]])

In [113]:
f<g

tensor([[False,  True, False],
        [ True,  True, False]])

In [114]:
f==g

tensor([[False, False, False],
        [False, False, False]])

In [115]:
f!=g

tensor([[True, True, True],
        [True, True, True]])

In [116]:
torch.log(f)

tensor([[2.0794, 1.3863, 1.9459],
        [0.6931, 1.0986, 2.0794]])

In [117]:
torch.exp(f)

tensor([[2980.9580,   54.5981, 1096.6332],
        [   7.3891,   20.0855, 2980.9580]])

In [118]:
torch.sqrt(f)

tensor([[2.8284, 2.0000, 2.6458],
        [1.4142, 1.7321, 2.8284]])

In [119]:
torch.sigmoid(f)

tensor([[0.9997, 0.9820, 0.9991],
        [0.8808, 0.9526, 0.9997]])

In [122]:
torch.softmax(f,dim=0)

tensor([[0.9526, 0.7311, 0.8808],
        [0.0474, 0.2689, 0.1192]])

In [123]:
torch.relu(f)

tensor([[4., 2., 7.],
        [1., 1., 5.]])

# inplace operations

In [124]:
m=torch.rand(2,3)
n=torch.rand(2,3)

In [125]:
m

tensor([[0.2131, 0.3957, 0.6017],
        [0.4234, 0.5224, 0.4175]])

In [126]:
n

tensor([[0.0340, 0.9157, 0.3079],
        [0.6269, 0.8277, 0.6594]])

In [127]:
m.add_(n)

tensor([[0.2472, 1.3114, 0.9096],
        [1.0504, 1.3501, 1.0769]])

In [128]:
m

tensor([[0.2472, 1.3114, 0.9096],
        [1.0504, 1.3501, 1.0769]])

# copy a tensor

In [129]:
m

tensor([[0.2472, 1.3114, 0.9096],
        [1.0504, 1.3501, 1.0769]])

In [130]:
b=m

In [131]:
m

tensor([[0.2472, 1.3114, 0.9096],
        [1.0504, 1.3501, 1.0769]])

In [132]:
# changes in original and copy if a=b / pointing a reference to that only

In [133]:
b=m.clone()

In [134]:
m[0][0]=0

In [135]:
m

tensor([[0.0000, 1.3114, 0.9096],
        [1.0504, 1.3501, 1.0769]])

In [136]:
b

tensor([[0.2472, 1.3114, 0.9096],
        [1.0504, 1.3501, 1.0769]])

In [2]:
import torch

# tensor operations on GPU

In [3]:
torch.cuda.is_available()

True

In [4]:
device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')

In [5]:
torch.rand(2,3).to(device)

tensor([[0.2242, 0.9691, 0.9623],
        [0.6287, 0.8554, 0.2607]], device='cuda:0')

In [6]:
torch.rand(2,3).to('cuda')

tensor([[0.1832, 0.4302, 0.3451],
        [0.0951, 0.0186, 0.9345]], device='cuda:0')

In [7]:
torch.rand((2,3),device=device)

tensor([[0.2598, 0.9168, 0.5217],
        [0.1115, 0.6140, 0.6916]], device='cuda:0')

# reshapiong the tensors

In [8]:
a=torch.ones(4,4)

In [9]:
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
a.reshape(8,2)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [11]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
b=torch.rand(2,3,4)

In [13]:
b

tensor([[[0.4487, 0.7244, 0.7001, 0.2979],
         [0.0075, 0.0811, 0.4203, 0.9424],
         [0.9166, 0.1231, 0.0687, 0.1868]],

        [[0.4346, 0.9351, 0.8024, 0.6894],
         [0.5108, 0.1723, 0.5011, 0.5483],
         [0.6117, 0.9728, 0.0192, 0.3491]]])

In [14]:
b.permute(2,0,1)

tensor([[[0.4487, 0.0075, 0.9166],
         [0.4346, 0.5108, 0.6117]],

        [[0.7244, 0.0811, 0.1231],
         [0.9351, 0.1723, 0.9728]],

        [[0.7001, 0.4203, 0.0687],
         [0.8024, 0.5011, 0.0192]],

        [[0.2979, 0.9424, 0.1868],
         [0.6894, 0.5483, 0.3491]]])

In [16]:
#unsqueeze
b=torch.rand(226,226,3)

In [17]:
b

tensor([[[4.6318e-01, 2.3867e-01, 9.9984e-01],
         [2.6226e-01, 7.3677e-02, 1.2659e-01],
         [9.1507e-01, 4.1627e-01, 7.7333e-01],
         ...,
         [6.3921e-01, 4.2557e-01, 3.4594e-01],
         [3.0854e-01, 8.5040e-01, 8.1422e-01],
         [1.8698e-02, 7.6351e-01, 2.1470e-01]],

        [[3.0986e-01, 2.1724e-01, 3.5800e-01],
         [1.8507e-01, 2.4158e-01, 4.2893e-01],
         [2.4869e-01, 6.1102e-02, 7.8638e-02],
         ...,
         [6.3448e-01, 2.1349e-01, 7.2390e-01],
         [9.7327e-02, 5.9249e-01, 1.0218e-01],
         [5.4829e-01, 3.0424e-01, 5.1072e-01]],

        [[6.1781e-01, 3.3711e-01, 9.1160e-01],
         [9.9719e-02, 2.8541e-01, 3.0008e-01],
         [9.5571e-03, 5.1483e-01, 8.0988e-01],
         ...,
         [5.6699e-01, 1.1409e-01, 7.9573e-01],
         [9.1791e-01, 6.4755e-01, 4.6385e-01],
         [9.7897e-01, 7.9375e-01, 9.9475e-01]],

        ...,

        [[4.8669e-02, 6.6204e-02, 6.7609e-01],
         [8.9720e-01, 2.9438e-02, 6.6943e-01]

In [18]:
b.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [19]:
b.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [20]:
b.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

In [23]:
b.shape

torch.Size([226, 226, 3])

In [25]:
#squeeze
b.squeeze(1).shape

torch.Size([226, 226, 3])

In [26]:
a=torch.rand(1,20)

In [27]:
a

tensor([[0.0352, 0.3126, 0.6372, 0.7970, 0.8882, 0.5556, 0.1482, 0.4697, 0.3468,
         0.5200, 0.4563, 0.3436, 0.4766, 0.3183, 0.4880, 0.7441, 0.2921, 0.0915,
         0.4277, 0.8373]])

In [28]:
a.squeeze(0).shape

torch.Size([20])

cobvert numpy to tensor

In [29]:
import numpy as np

In [30]:
a=torch.tensor([1,2,3])

In [31]:
a.type

<function Tensor.type>

In [32]:
a.dtype

torch.int64

In [33]:
b=a.numpy()

In [35]:
b.dtype

dtype('int64')

In [36]:
b

array([1, 2, 3])

In [37]:
a=np.array([1,2,3,3])

In [38]:
torch.from_numpy(a)

tensor([1, 2, 3, 3])